#!/usr/bin/env ruby
# Asks the user for temperature
print "Enter the temperature in Celsius: "
celsius = {format("%.2f") gets.chomp}
fahrenheit = celsius * (9.0 / 5.0) + 32
# Converts in Fahrenheit
puts "#{celsius} degrees Celsius -> #{fahrenheit} degrees Fahrenheit"

